name: prodaktiv
region: nyc
services:
  - name: web
    github:
      repo: fuego-wtf/prodaktiv
      branch: deploy/do-fullstack
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: LOOPS_API_KEY
        scope: RUN_TIME
        type: SECRET
